import http from 'node:http'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.dirname(fileURLToPath(import.meta.url))
const publicDir = path.join(root, 'dist')
const canonicalPath = path.join(root, 'server/data/ancp/generated/animal_records_one_row_per_animal.csv')
const manifestPath = path.join(root, 'server/data/ancp/table_manifest.csv')
const metricGroups = ['3P', 'MP120', 'MP210', 'P120', 'P210', 'P365', 'P450', 'PE365', 'STAY', 'AOL', 'ACAB', 'CAR', 'MAR', 'MGTe', 'MGTe_CR', 'MGTe_RE', 'MGTe_CO', 'MGTe_F1', 'IPP', 'PAC']
function parseCsvLine(line) { const out = []; let value = ''; let quoted = false; for (let i = 0; i < line.length; i += 1) { const char = line[i]; if (char === '"') { if (quoted && line[i + 1] === '"') { value += '"'; i += 1 } else quoted = !quoted } else if (char === ',' && !quoted) { out.push(value); value = '' } else value += char } out.push(value); return out }
function loadRows() { if (!fs.existsSync(canonicalPath)) return { headers: [], rows: [] }; const lines = fs.readFileSync(canonicalPath, 'utf8').split(/\r?\n/).filter(Boolean); const headers = parseCsvLine(lines[0]).map((item) => item.replace(/^\uFEFF/, '').trim()); return { headers, rows: lines.slice(1).map((line) => { const values = parseCsvLine(line); return Object.fromEntries(headers.map((header, index) => [header, values[index] ?? ''])) }) } }
const dataset = loadRows()
const manifest = fs.existsSync(manifestPath) ? fs.readFileSync(manifestPath, 'utf8') : ''
const breeds = [...new Set((manifest.match(/(?:Nelore|Guzerá|Brahman|Tabapuã|Sindi)/g) || []))]
const clean = (value) => String(value ?? '').trim()
const numeric = (value) => { const parsed = Number(String(value ?? '').replace(',', '.').replace('%', '')); return Number.isFinite(parsed) ? parsed : null }
function available(row, metric) { return Boolean(clean(row[`${metric}dep`]) || clean(row[`${metric}ac`]) || clean(row[`${metric}top_pct`])) }
function recommendation(params) { const required = params.required.filter(Boolean); const filtered = dataset.rows.filter((row) => { if (params.breed !== 'Todas' && clean(row.breed) !== params.breed) return false; const requiredMetrics = required.length ? required : (params.protect ? ['3P', 'STAY'] : []); if (requiredMetrics.some((metric) => !available(row, metric))) return false; const accuracyMetrics = requiredMetrics.length ? requiredMetrics : metricGroups; if (params.minAccuracy > 0 && accuracyMetrics.some((metric) => { const value = numeric(row[`${metric}ac`]); return value !== null && value < params.minAccuracy })) return false; const topMetrics = requiredMetrics.length ? requiredMetrics : metricGroups; if (params.maxTop < 100 && topMetrics.some((metric) => { const value = numeric(row[`${metric}top_pct`]); return value !== null && value > params.maxTop })) return false; for (const [metric, floor] of Object.entries(params.limits)) { const value = numeric(row[`${metric}dep`]); if (value !== null && value < floor) return false } return true })
  const weightTotal = Object.values(params.weights).reduce((sum, value) => sum + value, 0) || 100
  return filtered.map((row) => { const contributions = {}; let score = 0; for (const [metric, weight] of Object.entries(params.weights)) { const dep = numeric(row[`${metric}dep`]); const contribution = dep === null ? 0 : (dep / 100) * (weight / weightTotal) * 100; contributions[metric] = Math.round(contribution * 10) / 10; score += contribution } const metrics = metricGroups.filter((metric) => available(row, metric)).slice(0, 6); const missing = Object.keys(params.weights).filter((metric) => !available(row, metric)); return { name: clean(row.animal_name || row.NOME || row.name) || 'Registro sem nome', breed: clean(row.breed) || 'Não informado', page: clean(row.source_page || row.source_pages || row.page) || '—', score: Math.round(score * 10) / 10, metrics, contributions, alerts: missing.length ? [`Sem dado publicado para: ${missing.join(', ')}`] : [], tradeoffs: metrics.length ? `Resultado calculado com ${metrics.length} métricas disponíveis na tabela de origem.` : 'Poucas métricas disponíveis para este registro.' } }).sort((a, b) => b.score - a.score).slice(0, 20) }
function json(res, body, status = 200) { res.writeHead(status, { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store' }); res.end(JSON.stringify(body)) }
function serveStatic(req, res) { const requested = req.url === '/' ? '/index.html' : req.url.split('?')[0]; const file = path.normalize(path.join(publicDir, requested)); if (!file.startsWith(publicDir) || !fs.existsSync(file)) return json(res, { error: 'not_found' }, 404); const ext = path.extname(file); const types = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript', '.css': 'text/css', '.svg': 'image/svg+xml' }; res.writeHead(200, { 'content-type': types[ext] || 'application/octet-stream' }); fs.createReadStream(file).pipe(res) }
const server = http.createServer((req, res) => { const url = new URL(req.url || '/', `http://${req.headers.host || 'localhost'}`); if (url.pathname === '/api/health') return json(res, { ok: true, service: 'melhor-genetica', dataRows: dataset.rows.length }); if (url.pathname === '/api/catalog') return json(res, { edition: 'ANCP 2026', rows: dataset.rows.length, breeds, source: 'Sumário de Touros ANCP 2026', tables: 59, columns: dataset.headers.length }); if (url.pathname === '/api/recommend') { let weights = { '3P': 40, 'MP120': 25, 'STAY': 20, 'MGTe': 15 }; try { if (url.searchParams.get('weights')) weights = JSON.parse(url.searchParams.get('weights')) } catch {} let limits = {}; try { if (url.searchParams.get('limits')) limits = JSON.parse(url.searchParams.get('limits')) } catch {} const params = { breed: url.searchParams.get('breed') || 'Todas', minAccuracy: numeric(url.searchParams.get('minAccuracy')) ?? 0, maxTop: numeric(url.searchParams.get('maxTop')) ?? 100, protect: url.searchParams.get('protect') === 'true', required: (url.searchParams.get('required') || '').split(',').filter(Boolean), limits, weights }; return json(res, { ...params, total: recommendation(params).length, recommendations: recommendation(params) }) } return serveStatic(req, res) })
const port = Number(process.env.PORT || 3000)
server.listen(port, () => console.log(`Melhor Genética listening on port ${port}`))
